name: UAT CI/CD Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      pp_environment: ${{ steps.set-vars.outputs.pp_environment }}
      solutions: ${{ steps.set-vars.outputs.solutions }}
    steps:
      - name: Set UAT environment variables
        id: set-vars
        run: |
          echo "pp_environment=${{ secrets.POWER_PLATFORM_UAT_URL }}" >> $GITHUB_OUTPUT
          echo "solutions=${{ secrets.SOLUTION_LIST_UAT }}" >> $GITHUB_OUTPUT
          
          echo "âœ“ Loaded UAT environment: ${{ secrets.POWER_PLATFORM_UAT_URL }}"

  deploy:
    needs: prepare
    uses: Himaan1502/PowerApps-GitHubActions/.github/workflows/powerapps-reusable.yml@main
    with:
      pp_environment: ${{ needs.prepare.outputs.pp_environment }}
      solutions: ${{ needs.prepare.outputs.solutions }}
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
